### PR TITLE
[#26] Start fixing linter issues

### PR DESCRIPTION
**Pull request by askorutin26**
Tried to fix some issues, the most part was fixed using --fix option of eslint.

I'm not sure how to fix "react/prop-types", maybe disable this rule? 
As for "import/no-extraneous-dependencies" says '@storybook/react' should be listed in the project's dependencies, not devDependencies', i've found answer that this rule may be disabled as well.

### CODE REVIEW

**Comment by dolby360** [comment]
@askorutin26 I'm deeply apologies, I didn't see your pull request.
is it ready for merge?

Thank you very much for contributing.

**Comment by dolby360** [comment]
Don't worry about the tests I don't like them anyway.
I need to find another way to test this project.
@askorutin26

**Comment by dolby360** [comment]
> Tried to fix some issues, the most part was fixed using --fix option of eslint.
> 
> I'm not sure how to fix "react/prop-types", maybe disable this rule? As for "import/no-extraneous-dependencies" says '@storybook/react' should be listed in the project's dependencies, not devDependencies', i've found answer that this rule may be disabled as well.

Can you please upload another PR to disable them?

**Comment by dolby360** [comment]
@all-contributors please add @askorutin26  for code

**Comment by askorutin26** [comment]
@dolby360 Thank you for accepting PR! Sure, I will add rules for disabling soon.

**Comment by dolby360** [comment]
@askorutin26 your contribution is very much appreciated, please consider to give a star :)

**Pull request merged**
