### PR TITLE
Replace vars with const and let

### PR DESCRIPTION
**Pull request by Tamir198**

### CODE REVIEW

**Comment by Tamir198** [comment]
This commit is regarding issue #6

**Comment by dolby360** [comment]
@Tamir198 Thank you very much for you contribution.
I will check this change locally since we still don't have a test pipline. 
(I opened an issue for that  https://github.com/dolby360/hex_color_displayer/issues/12).

**Comment by dolby360** [comment]
I had just one issue there.
After the fix, we will be able to merge.
Thanks again

**Comment by dolby360** [comment]
@Tamir198 need help?

**Comment by Tamir198** [comment]
@dolby360  Oops, I haven't noticed the conflicts. I resolved them now.

**Comment by dolby360** [comment]
> @dolby360 Oops, I haven't noticed the conflicts. I resolved them now.

@Tamir198 and there is also a small bug :)

**Comment by Tamir198** [comment]
@dolby360  What bug?

**Comment by dolby360** [comment]
> @dolby360 What bug?

@Tamir198 Please see in the code review I set a note. You used a const instead of "let"

**Comment by Tamir198** [comment]
I don't see any code review submitted on my pr

**Comment by dolby360** [comment]
> I don't see any code review submitted on my pr

@Tamir198 
image

**Comment by Tamir198** [comment]
@dolby360 yes, sorry but I could not find the time for this, I had a busy couple of days.

**Comment by Tamir198** [comment]
@dolby360  Is it ok now?

**Comment by dolby360** [comment]
@Tamir198 Thank you very much for your contribution.
There are a few bugs that I'll solve after the merge (I can't edit this PR).

**Comment by dolby360** [comment]
@all-contributors please add @Tamir198  for code

**Pull request merged**
